id: I899A2091
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T10:05:15+00:00'
last_modified: '2022-06-08T16:53:41.359925+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21680
  title: བྷེ་གླིང་གཡུལ་འགྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    AF3A:
      image_group_id: I1KG17073
      title: ''
      total_pages: 400
      order: 1
      base_file: AF3A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
