id: P010699
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W21680
  title: བྷེ་གླིང་གཡུལ་འགྱེད།
  author: ''
  volumes:
    f9ac318a9f1e4ac08481fb63337eee6d:
      image_group_id: I1KG17073
      title: ''
      volume_number: 1
      total_pages: 400
      base_file: v001.txt
